In [50]:
import numpy as np

In [51]:
x= np.array([2,3,4,5])
y= np.array([3,4,7,1])

In [52]:
z= np.log(x)
print(z)


[0.69314718 1.09861229 1.38629436 1.60943791]


In [53]:
z= np.exp(y)
print(z)


[  20.08553692   54.59815003 1096.63315843    2.71828183]


In [54]:
z= np.sqrt(x)
print(z)


[1.41421356 1.73205081 2.         2.23606798]


In [55]:
z= np.dot(x,y)
z= x.dot(y)
print(z)


51


In [56]:
z= np.linalg.norm(a)
print(z)



12.806248474865697


In [57]:
cosangle= x.dot(y) / np.linalg.norm(x) * np.linalg.norm(y)
print(cosangle)


60.10407640085655


In [58]:
angle = np.arccos(0.90)
print(angle)


0.45102681179626236


In [59]:
x = np.matrix([[4,5,7],[8,1,3]])
print(x)
print(x[1,1])
a = np.array(x)
print(a)
print(a.T)



[[4 5 7]
 [8 1 3]]
1
[[4 5 7]
 [8 1 3]]
[[4 8]
 [5 1]
 [7 3]]


In [60]:
z = np.zeros(8)
print(z)



[0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
m = np.zeros((1,1))
print(m)


[[0.]]


In [62]:
o = np.ones((2,2))
print(o)


[[1. 1.]
 [1. 1.]]


In [63]:
r = np.random.random((2,2))
print(r)


[[0.89132108 0.12833736]
 [0.86551638 0.33951352]]


In [64]:
h = np.random.randn(2,2)
print(h)


[[ 0.31549531  1.65839919]
 [-0.19838438  0.6966307 ]]


In [65]:
print(h.mean())
print(h.var())


0.6180352042424176
0.46165145475171526


In [66]:
p = np.array([[3,5,7],[3,5,1],[7,8,3]])
q = np.array([[5,6],[1,2],[6,7]])






In [67]:
r = p.dot(q)
print(r)




[[62 77]
 [26 35]
 [61 79]]


In [68]:
pinv = np.linalg.inv(p)
print(pinv)


[[-1.06060606e-01 -6.21212121e-01  4.54545455e-01]
 [ 3.03030303e-02  6.06060606e-01 -2.72727273e-01]
 [ 1.66666667e-01 -1.66666667e-01 -7.93016446e-18]]


In [69]:
correct = p.dot(pinv)
print(correct)


[[1.00000000e+00 1.11022302e-16 3.08148791e-33]
 [0.00000000e+00 1.00000000e+00 4.75809868e-17]
 [2.77555756e-17 1.11022302e-16 1.00000000e+00]]


In [70]:
d = np.linalg.det(p)
print(d)


-65.99999999999997


In [71]:
di = np.diag(p)
print(di)


[3 5 3]


In [72]:
x = np.trace(x)
print(x)


5
